# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build aws-delegation53 docker

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    #runs-on: ["self-hosted", "Linux", "ARM64" ]
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      name: docker builder
      with:
        fetch-depth: 10

    - name: "build docker fastandfearless/aws-delegation53"
      run: |
        curl -L -o ./neckless https://github.com/mabels/neckless/releases/download/v0.1.3/default.neckless-linux-amd64
        chmod +x ./neckless
        ./neckless kv --file ./.neckless ls -onlyValue DOCKER_SECRET | docker login --username fastandfearless --password-stdin
        GITVER=$(git rev-parse --short HEAD)
        docker build . -t fastandfearless/aws-delegation53:$GITVER
        docker push fastandfearless/aws-delegation53:$GITVER
        docker tag fastandfearless/aws-delegation53:$GITVER fastandfearless/aws-delegation53:latest
        docker push fastandfearless/aws-delegation53:latest

      env:
        NECKLESS_PRIVKEY: ${{ secrets.NECKLESS_PRIVKEY }}
